version: '3'

tasks:
  build:
    cmds:
      - mkdir -p bin && source .env && CGO_ENABLED=0 GOOS=linux go build -a -o bin/zstore ./cmd

  test:
    cmds:
      - source .env && go test -v ./...

  lint:
    cmds:
      - golangci-lint run

  run:
    cmds:
      - source .env && ./bin/zstore

